hrms/urls.py
from django.contrib import admin  
from django.urls import path  
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from django.conf import settings

class Employee_Attendance(models.Model):
    emp = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    timeIn = models.DateField(auto_now_add=True)
    timeOut = models.DateField()
    remarks = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.emp
    

class Leaves(models.Model):
    leaveName = models.CharField(max_length=255)
    days = models.IntegerField()

    def __str__(self):
        return self.leaveName


class Employee_Leaves(models.Model):
    empId = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    leaveId = models.ForeignKey(Leaves, on_delete=models.CASCADE, null=True, blank=True)
    startDate = models.DateField()
    EndDate = models.DateField()
    totalDays = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.emp} - {self.leaveId}"


class News(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.title    

class Holiday(models.Model):
    title = models.CharField(max_length=100)
    startDate = models.DateField()
    endDate = models.DateField()
    createDate = models.DateField(auto_now=True)
    description = models.TextField()

    def __str__(self):
        return self.title    


class Employee_Trainings(models.Model):
    emp = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    skills = models.CharField(max_length=255)
    training = models.CharField(max_length=100)
    projectReqt = models.CharField(max_length=100)
    bond = models.IntegerField()

    def __str__(self):
        return f"{self.emp} - {self.skills}"


class Employee_Salary(models.Model):
    emp = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    salaryRange = models.CharField(max_length=100)
    annualIncome = models.IntegerField()
    taxable = models.IntegerField()
    loans = models.IntegerField()
    insurance = models.IntegerField()

    def __str__(self):
        return f"{self.emp} - {salaryRange}"
    

class Position(models.Model):
    positionName = models.CharField(max_length=100)

    def __str__(self):
        return self.positionName
    

class Department(models.Model):
    departmentName = models.CharField(max_length=100)

    def __str__(self):
        return self.departmentName


class Employee_Project(models.Model):
    emp = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    projectHandled = models.CharField(max_length=100)
    dateStarted = models.DateField()
    dateEnded = models.DateField()
    status = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.emp} - {self.projectHandled} "


class Employee_Details(models.Model):
    GENDER_CHOICES = (
        ("", "Select Gender"),
        ("Male", "Male"),
        ("Female", "Female")
    )

    emp = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    firstName = models.CharField(max_length=100)
    middleName = models.CharField(max_length=100, null=True, blank=True, default="")
    lastName = models.CharField(max_length=100, null=True, blank=True, default="")
    deptId = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True)
    positionId = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True) 
    birthDate = models.DateField()
    age = models.IntegerField()
    sex = models.CharField(max_length=10, choices=GENDER_CHOICES, default="")
    address = models.CharField(max_length=255)
    employedDate = models.DateField()
    supervisorId = models.ForeignKey(User, on_delete=models.CASCADE, related_name='supervised_employees', null=True, blank=True) 
    img = models.ImageField(upload_to='employee', null=True, blank=True)

    def __str__(self):
        return f"{self.firstName} {self.middleName} {self.lastName}"

templates/attendance.html
{% extends "dashboard.html" %}
{% block title1 %}Attendance{% endblock title1 %}


{% block dashboard %}

    <h1>Employee</h1>
    <p>Hi, {{emp.firstName}} {{emp.middleName}} {{emp.lastName}}</p>
    <p>Department : {{emp.deptId}}</p>
    <p>Position : {{emp.positionId}}</p>
    <p>Date of Birth : {{emp.birthDate}}</p>
    <p>Age : {{emp.age}}</p>
    <p>Gender : {{emp.sex}}</p>
    <p>Address : {{emp.address}}</p>
    <p>Joining Date : {{emp.employedDate}}</p>
    <p>Supervisor : 
        {% if emp.supervisorId is 'admin' %}
            {{emp.supervisorId}}
        {% else %}
            Self
        {% endif %}</p>
    
{% endblock dashboard %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block body %}
        <h1>Base Page</h1>
    {% endblock body %}

    <script>
        {% if message %}
            alert({{message}})
        {% endif %}
        {% block script %}{% endblock script %}
    </script>
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block title %}
    {% block title1 %}Dashboard{% endblock title1 %}
{% endblock title %}

{% block body %}
    <h1>Dashboard</h1>
    <ul>
        <li><a href='{% url "dashboard" %}'>Dashboard</a></li>
        <li><a href='{% url "employee" %}'>Employee</a></li>
        <li><a href='{% url "leave" %}'>Leave</a></li>
        <li><a href='{% url "attendance" %}'>Attendance</a></li>
        <li><a href='{% url "holiday" %}'>Holiday</a></li>
    </ul>

    <h2>Welcome to Dashboard Page {{request.user}}</h2>
    {% block dashboard %}{% endblock dashboard %}
    
    <a href='{% url "logout" %}'>Logout</a>
{% endblock body %}

templates/employee.html
{% extends "dashboard.html" %}
{% block title1 %}Employee{% endblock title1 %}


{% block dashboard %}

    <h1>Employee</h1>
    <p>Hi, {{emp.firstName}} {{emp.middleName}} {{emp.lastName}}</p>
    <p>Department : {{emp.deptId}}</p>
    <p>Position : {{emp.positionId}}</p>
    <p>Date of Birth : {{emp.birthDate}}</p>
    <p>Age : {{emp.age}}</p>
    <p>Gender : {{emp.sex}}</p>
    <p>Address : {{emp.address}}</p>
    <p>Joining Date : {{emp.employedDate}}</p>
    <p>Supervisor : 
        {% if emp.supervisorId is 'admin' %}
            {{emp.supervisorId}}
        {% else %}
            Self
        {% endif %}</p>
    
{% endblock dashboard %}

templates/holiday.html
{% extends "dashboard.html" %}
{% block title1 %}Holiday{% endblock title1 %}


{% block dashboard %}
    <h2>Holidays</h2>
    {% if holidays %}
        <table style='width:80%; margin:auto;' border='1'>
            <tr>
                <th>Title</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Description</th>
            </tr>
            {% for holiday in holidays %}
            <tr>
                <td>{{holiday.title}}</td>
                <td>{{holiday.startDate}}</td>
                <td>{{holiday.endDate}}</td>
                <td>{{holiday.description}}</td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
    
{% endblock dashboard %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}

{% block body %}
    <h1>Home Page</h1>
    <a href='{% url "signin" %}'>SignIn</a>
    <a href='{% url "signup" %}'>SignUp</a>
{% endblock body %}

templates/leave.html
{% extends "dashboard.html" %}
{% block title1 %}Leave{% endblock title1 %}


{% block dashboard %}

    <h1>Employee</h1>
    <p>Hi, {{emp.firstName}} {{emp.middleName}} {{emp.lastName}}</p>
    <p>Department : {{emp.deptId}}</p>
    <p>Position : {{emp.positionId}}</p>
    <p>Date of Birth : {{emp.birthDate}}</p>
    <p>Age : {{emp.age}}</p>
    <p>Gender : {{emp.sex}}</p>
    <p>Address : {{emp.address}}</p>
    <p>Joining Date : {{emp.employedDate}}</p>
    <p>Supervisor : 
        {% if emp.supervisorId is 'admin' %}
            {{emp.supervisorId}}
        {% else %}
            Self
        {% endif %}</p>
    
{% endblock dashboard %}

templates/login.html
{% extends "base.html" %}

{% block title %}SignIn{% endblock title %}

{% block body %}
    <div class="login-form">
        <h3>Login Page</h3>
        <form method="post" novalidate>
            {% csrf_token %}
            <div class="field">
                <label for="id_username">{{ form.username.label }}</label>
                {{ form.username }}
                {{ form.username.help_text }}
                <span class="form-error">{{ form.username.errors }}</span>
            </div>
            <div class="field">
                <label for="id_password">{{ form.password.label }}</label>
                {{form.password}}
                {{form.password.help_text}}
                <span class="form-error">{{form.password.errors}}</span>
            </div>
            <div class="field button-field">
                <input type="submit" value="Login">
                <input type="reset" value="Reset">
            </div>
        </form>
    </div>
{% endblock body %}

{% block script %}
    {% if message %}
        alert({{message}})
    {% endif %}
{% endblock script %}

templates/signup.html
{% extends "base.html" %}


{% block title %}SignUp{% endblock title %}

{% block body %}

<div class="signup-form">
    <h3>Add Employee</h3>
    {% for error in form.erros %}
        <span style='color:red;'>{{error}}</span>
    {% endfor %}
    <form method='post' novalidate>
        {% csrf_token %}
        <div class="container-signup">
        <div class=row>
            <div class="field">
                <label for='id_username' class='form_label'>Username</label>
                {{form.username}}
                {{form.username.errors}}
            </div>
            
            <div class="field">
                <label for='id_firstName' class='form_label'>First Name</label>
                {{emp_form.firstName}}
                {{emp_form.firstName.errors}}
            </div>
            <div class="field">
                <label for='id_middleName' class='form_label'>Middle Name</label>
                {{emp_form.middleName}}
                {{emp_form.middleName.errors}}
            </div>
            <div class="field">
                <label for='id_lastName' class='form_label'>Last Name</label>
                {{emp_form.lastName}}
                {{emp_form.lastName.errors}}
            </div>
            <div class="field">
                <label for='id_deptId' class='form_label'>Department</label>
                {{emp_form.deptId}}
                {{emp_form.deptId.errors}}
            </div>
            <div class="field">
                <label for='id_positionId' class='form_label'>Position</label>
                {{emp_form.positionId}}
                {{emp_form.positionId.errors}}
            </div>
            <div class="field">
                <label for='id_birthDate' class='form_label'>Date of Birth</label>
                {{emp_form.birthDate}}
                {{emp_form.birthDate.errors}}
            </div>
            <div class="field">
                <label for='id_age' class='form_label'>Age</label>
                {{emp_form.age}}
                {{emp_form.age.errors}}
            </div>
            <div class="field">
                <label for='id_sex' class='form_label'>Gender</label>
                {{emp_form.sex}}
                {{emp_form.sex.errors}}
            </div>
        </div>
        <div class=row>
            
            <div class="field">
                <label for='id_address' class='form_label'>Address</label>
                {{emp_form.address}}
                {{emp_form.address.errors}}
            </div>
            <div class="field">
                <label for='id_employedDate' class='form_label'>Started Date</label>
                {{emp_form.employedDate}}
                {{emp_form.employedDate.errors}}
            </div>
            <div class="field">
                <label for='id_supervisorId' class='form_label'>Supervisor</label>
                {{emp_form.supervisorId}}
                {{emp_form.supervisorId.errors}}
            </div>
            <div class="field">
                <label for="id_img" class="drop-container" id="dropcontainer">
                    <span class="drop-title">Drop files here</span>
                    or
                    {{emp_form.img}}
                </label> 
                {{emp_form.img.errors}}
            </div>
            <div class="field">
                <label for='id_password1' class='form_label'>Password</label>
                {{form.password1}}
                {{form.password1.errors}}
            </div>
            <div class="field">
                <label for='id_password2' class='form_label'>Confirm Password</label>
                {{form.password2}}
                {{form.password2.errors}}
            </div>
        </div>
        </div>

        
        <div class="field button-field">
            <input type="submit" value="Create">
            <input type="reset" value="Reset">
        </div>
    </form>
</div>
{% endblock body %}


{% block script %}




    const dropContainer = document.getElementById("dropcontainer")
    const fileInput = document.getElementById("images")

    dropContainer.addEventListener("dragover", (e) => {
    e.preventDefault()
    }, false)

    dropContainer.addEventListener("dragenter", () => {
    dropContainer.classList.add("drag-active")
    })

    dropContainer.addEventListener("dragleave", () => {
    dropContainer.classList.remove("drag-active")
    })

    dropContainer.addEventListener("drop", (e) => {
    e.preventDefault()
    dropContainer.classList.remove("drag-active")
    fileInput.files = e.dataTransfer.files
    })
{% endblock script %}